FROM bellsoft/liberica-native-image-kit-container:jdk-22-nik-24.0.2-glibc as builder
WORKDIR /home/build
COPY . /home/build/
RUN ./mvnw clean package -DskipTests

FROM bellsoft/liberica-runtime-container:jdk-21.0.4-crac-cds-slim-glibc
WORKDIR /home/myapp
COPY --from=builder /home/build/target/flutter-flex-backend.jar .
EXPOSE 8080
CMD ["java", "-jar", "/home/myapp/flutter-flex-backend.jar"]