server:
  port: 8080

spring:
  application:
    name: flutter-flex-backend
  profiles:
    active: dev

mytool:
  view:
    page: /view/**
  upload:
    path: /home/mytool

logging:
  file:
    path: logs
  level:
    com:
      zaxxer:
        hikari: DEBUG
