server:
  port: 8080

spring:
  application:
    name: flutter-flex-backend
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:group.mytool.flutter.flex.backend.*.*.mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    path: logs